### PR TITLE
Issue #1 and Issue #6

### PR DESCRIPTION
**Pull request by LalitSharma7**
Please check it

### CODE REVIEW

**Review by vijeta1 — COMMENTED** [review]
submit one liner script for task-6

**Comment by LalitSharma7** [comment]
@vijeta1 check it

**Comment by vijeta1** [comment]
solution of task-6 is wrong

**Comment by LalitSharma7** [comment]
@vijeta1 you can merge the first issue if it is correct and i am actually working on some other issue that's why not getting time to work on other tasks given.

**Pull request merged**
