### PR TITLE
Week 1 tasks

### PR DESCRIPTION
**Pull request by vaibhav-1207**

### CODE REVIEW

**Review by vijeta1 — COMMENTED** [review]
In order to complete this task use linux command

**Review by vijeta1 — COMMENTED** [review]
above comment is for task-1

**Comment by vaibhav-1207** [comment]
i have used linux commands now

**Review by amriteshbhaskar — COMMENTED** [review]
It's wrong, we'll not accept it. please run it before submitting.

**Comment by vaibhav-1207** [comment]
> It's wrong, we'll not accept it. please run it before submitting.

@amriteshbhaskar which one sir?

**Comment by vaibhav-1207** [comment]
@amriteshbhaskar I have submitted all the snapshots of my linux terminal.

**Pull request merged**
