### PR TITLE
add contestant nikolai6303

### PR DESCRIPTION
**Pull request by bettercalln1ck**

### CODE REVIEW

**Review by vijeta1 — COMMENTED** [review]
nikolai6303 change title of PR and also do command line interface for task-1

**Comment by vijeta1** [comment]
change title of PR and use command line interface for task-1 and resubmit your task

**Comment by vijeta1** [comment]
change title of PR and use command line interface for task-1 and resubmit your task

**Comment by bettercalln1ck** [comment]
sir,then what title should i put of pr?

**Comment by vijeta1** [comment]
like week-1 task for or mention issues which you fix.

**Pull request closed without merging**
